version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.3
    container_name: zookeeper
    networks: [spring-net]
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.3
    container_name: kafka
    depends_on: [zookeeper]
    networks: [spring-net]
    ports: ["9092:9092", "29092:29092"]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  crud-service:
    build: ./crud-service
    container_name: crud-service
    networks: [spring-net]
    ports: ["8080:8080"]
    depends_on: [kafka]

  booking-service:
    build: ./booking-service
    container_name: booking-service
    networks: [spring-net]
    ports: ["8081:8081"]
    depends_on: [kafka, crud-service]
    environment:
      CRUD_SERVICE_URL: http://crud-service:8080
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

networks:
  spring-net:
    driver: bridge
