server:
  port: 8081

spring:
  application:
    name: booking-service
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

crud-service:
  url: http://crud-service:8080 # For Docker Compose