global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "crud-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["crud-service:8080"]

  - job_name: "booking-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["booking-service:8081"]
