openapi: 3.0.1
info:
  title: Hotel CRUD API
  version: 1.0.0
  description: API contract for hotel CRUD operations.
servers:
  - url: http://localhost:8080
paths:
  /hotels:
    get:
      summary: List all hotels
      responses:
        "200":
          description: A list of hotels
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Hotel"
    post:
      summary: Create a new hotel
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Hotel"
      responses:
        "201":
          description: Hotel created
  /hotels/{id}:
    get:
      summary: Get a hotel by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Hotel details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Hotel"
        "404":
          description: Hotel not found
    put:
      summary: Update a hotel by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Hotel"
      responses:
        "200":
          description: Hotel updated
        "404":
          description: Hotel not found
    delete:
      summary: Delete a hotel by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Hotel deleted
        "404":
          description: Hotel not found
components:
  schemas:
    Hotel:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          minLength: 2
          maxLength: 100
        address:
          type: string
          minLength: 5
          maxLength: 255
        city:
          type: string
          maxLength: 100
        country:
          type: string
          maxLength: 100
        rating:
          type: number
          format: float
          minimum: 0
          maximum: 5
        totalRooms:
          type: integer
          minimum: 1
          maximum: 10000
        pricePerNight:
          type: number
          format: float
          minimum: 0
          maximum: 100000
        phoneNumber:
          type: string
          maxLength: 20
        email:
          type: string
          format: email
          maxLength: 100
        description:
          type: string
          maxLength: 1000
        amenities:
          type: string
          maxLength: 1000
        checkInTime:
          type: string
          pattern: "^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$"
        checkOutTime:
          type: string
          pattern: "^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$"
        isActive:
          type: boolean
          default: true
      required:
        - name
        - address
        - city
        - country
        - rating
        - totalRooms
        - pricePerNight
        - checkInTime
        - checkOutTime
